# Generated by Django 5.0 on 2023-12-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
